
import { useState } from 'react';
import { ComunidadVecinos } from '@/types';
import { useComunidadesVecinos } from './useComunidadesVecinos';

export const useComunidadForm = () => {
  const { createComunidad, isLoading } = useComunidadesVecinos();
  const [formData, setFormData] = useState<ComunidadVecinos>({
    id: '', // This will be generated by Firebase
    nombre: '',
    direccion: '',
    cif: '',
    codigoPostal: '',
    ciudad: '',
    distrito: '',
    barrio: '',
    numViviendas: 0, // Ensure this is a number
    totalViviendas: 0, // Ensure this is a number
    numeroPorteria: '',
    nombreAdministracion: '',
    correoContacto: '',
    litrosRecogidos: 0,
    beneficiosMedioambientales: {
      co2: 0,
      agua: 0,
      arboles: 0,
      energia: 0
    },
    createdAt: null, // Initialize with null
    updatedAt: null // Initialize with null
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    const numericFields = ['numViviendas', 'totalViviendas', 'litrosRecogidos'];
    
    setFormData(prev => ({
      ...prev,
      [name]: numericFields.includes(name) ? Number(value) : value
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    createComunidad({
      ...formData,
      numViviendas: Number(formData.numViviendas || 0),
      totalViviendas: Number(formData.totalViviendas || 0),
      numeroPorteria: formData.numeroPorteria ? String(formData.numeroPorteria) : ''
    });
  };

  return {
    formData,
    isLoading,
    handleChange,
    handleSubmit
  };
};
